<a href="https://colab.research.google.com/github/SujahathMSM/Pytorch-DeepLearning/blob/main/001_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fudamentals

In [1]:
print("Welcome to Pytorch")

Welcome to Pytorch


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors
#**Scaler**

In [4]:
#scaler
scaler = torch.tensor(9)
scaler

tensor(9)

In [5]:
scaler.item()

9

In [6]:
scaler.ndim

0

In [7]:
#Vector
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([4])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Creating Tensors