<a href="https://colab.research.google.com/github/SujahathMSM/Pytorch-DeepLearning/blob/main/TokenEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!!pip install gensim

['Collecting gensim',
 '  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)',
 'Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)',
 'Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)',
 'Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)',
 'Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)',
 'Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)',
 '\x1b[?25l   \x1b━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b \x1b0.0/27.9 MB\x1b \x1b?\x1b eta \x1b-:--:--\x1b',
 '\x1b[2K   \x1b━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b \x1b0.3/27.9 MB\x1b \x1b8.6 MB/s\x1b eta \x1b0:00:04\x1b',
 '\x1b[2K   \x1b━━━\x1b\x1b╸\x1b\x1b━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
import gensim.downloader as api
from gensim.models import KeyedVectors

In [3]:
print("Downloading model...")
wv = api.load('word2vec-google-news-300')
print("Model loaded successfully!")

[==================================================] 100.0% 1662.8/1662.8MB downloaded
Model loaded successfully!


In [4]:
print(wv['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [5]:
similar_words = wv.most_similar('python')
print(f"Words most similar to 'python': {similar_words[:3]}")

Words most similar to 'python': [('pythons', 0.66883784532547), ('Burmese_python', 0.6680365800857544), ('snake', 0.6606292724609375)]


In [6]:
vector = wv['computer']
print(f"Vector shape for 'computer': {vector.shape}")

Vector shape for 'computer': (300,)


In [7]:
word = "banana"
if word in wv:
    print(f"{word} is in the vocabulary.")
else:
    print(f"{word} is not in the vocabulary.")

banana is in the vocabulary.


In [8]:
similarity = wv.similarity('woman', 'man')
print(f"Similarity between 'woman' and 'man': {similarity}")

Similarity between 'woman' and 'man': 0.7664012312889099


In [9]:
result = wv.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)
print(f"Result of 'king' - 'man' + 'woman': {result[0]}")

Result of 'king' - 'man' + 'woman': ('queen', 0.7118193507194519)


In [10]:
similarity = wv.similarity('apple', 'banana')
print(f"Similarity between 'apple' and 'banana': {similarity}")

Similarity between 'apple' and 'banana': 0.5318406224250793


In [11]:
print(wv['Apple'])

[-1.74804688e-01  3.00292969e-02 -2.16796875e-01  1.56250000e-01
 -3.57421875e-01 -6.05468750e-02  1.36718750e-01  9.57031250e-02
  3.17382812e-03 -4.29687500e-02 -3.30078125e-01  2.57812500e-01
  2.51953125e-01 -2.77343750e-01 -6.98242188e-02 -2.95410156e-02
  3.22265625e-01 -7.76367188e-02 -3.06396484e-02 -1.67968750e-01
 -5.76171875e-02  3.05175781e-02  5.52368164e-03 -1.26953125e-01
 -1.44042969e-02  1.75781250e-01  9.47265625e-02  3.16406250e-01
 -7.81250000e-03 -3.40270996e-03  3.63769531e-02  1.11816406e-01
 -1.24023438e-01  1.29882812e-01 -3.22265625e-02 -1.60156250e-01
  7.56835938e-02  6.73828125e-02  4.08203125e-01  2.23632812e-01
  1.60156250e-01  3.63769531e-02 -1.64062500e-01 -3.51562500e-01
  4.49218750e-02  6.34765625e-02 -1.15234375e-01  3.12500000e-01
 -2.80761719e-02 -9.22851562e-02  5.98144531e-02  1.57470703e-02
 -1.15234375e-01  2.18750000e-01 -5.78613281e-02  2.07031250e-01
 -1.03515625e-01 -2.07031250e-01 -7.08007812e-02 -7.47070312e-02
  1.35742188e-01  1.80664

In [12]:
similarity = wv.similarity('Apple', 'apple')
print(f"Similarity between 'Apple' and 'apple': {similarity}")

Similarity between 'Apple' and 'apple': 0.3786771595478058


In [13]:
result = wv.most_similar(positive=['woman', 'king'], negative=['man'], topn=5)
print(f"Result of 'king' - 'man' + 'woman': {result}")

Result of 'king' - 'man' + 'woman': [('queen', 0.7118193507194519), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321839332581)]


In [14]:
result = wv.most_similar(positive=['RAM', 'Monitor', 'Keyboard'], negative=['Keyboard'], topn=5)
print(result)

[('By_JARED_JANES', 0.5405739545822144), ('By_VICTORIA_SHOULDIS', 0.538179874420166), ('By_JARED_TAYLOR', 0.5252323150634766), ('By_MADDIE_HANNA', 0.5242959856987), ('CPU_RAM', 0.5191538333892822)]


In [15]:
result = wv.most_similar(positive=['computer', 'mouse'], negative=['keyboard'], topn=5)
print(result)

[('computers', 0.5381786227226257), ('Computer', 0.4286578595638275), ('com_puter', 0.422382116317749), ('supercomputer', 0.4029233753681183), ('imagery_CGI', 0.39922839403152466)]


In [16]:
result = wv.most_similar(positive=['Rice', 'Curry', 'Chicken', 'vegetables'], negative=['banana'], topn=5)
print(result)

[('Lamb', 0.5187926888465881), ('Sausage_Gumbo', 0.5086236596107483), ('Spicy_Chicken', 0.5070229172706604), ('Cucumber_Salad', 0.4927563965320587), ('Tamale_Pie', 0.49156540632247925)]


In [17]:
result = wv.similar_by_word('Car', topn=5)
print(result)

[('car', 0.6677608489990234), ('Auto', 0.6563326716423035), ('Vehicle', 0.6293455362319946), ('Cars', 0.6291522979736328), ('##V_Midsize_Car', 0.621805727481842)]


In [18]:
result = wv.most_similar(positive=['Game', 'PC'], negative=['Keyboard'], topn=5)
print(result)

[('game', 0.4386070966720581), ('Thrones_Genesis', 0.4253532290458679), ('Game1', 0.42441362142562866), ('Tokyo_Masanori_Murakami', 0.407493531703949), ('PlayStation', 0.40423259139060974)]


In [19]:
import numpy as np

word1 = "man"
word2 = "woman"

word3 = "semiconductor"
word4 = "earthworm"

word5 = "nephew"
word6 = "niece"

#cosine similarity
def cosine_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

v1 = wv[word1]
v2 = wv[word2]

v3 = wv[word3]
v4 = wv[word4]

v5 = wv[word5]
v6 = wv[word6]

cos_sim_1 = cosine_similarity(v1, v2)
cos_sim_2 = cosine_similarity(v3, v4)
cos_sim_3 = cosine_similarity(v5, v6)

print(f"Cosine similarity ({word1}, {word2}): {cos_sim_1:.4f}")
print(f"Cosine similarity ({word3}, {word4}): {cos_sim_2:.4f}")
print(f"Cosine similarity ({word5}, {word6}): {cos_sim_3:.4f}")


Cosine similarity (man, woman): 0.7664
Cosine similarity (semiconductor, earthworm): 0.0267
Cosine similarity (nephew, niece): 0.7594


In [20]:
import torch

In [21]:
input_ids = torch.tensor([2, 3, 5,1])

In [22]:
vocab_size = 6
output_dim = 3

In [23]:
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [24]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [26]:
print(embedding_layer(torch.tensor([2])))

tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)


In [27]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
